version: '3.9'
services:
  
  db:
    image: fontyssa/postgres-extended
    restart: always
    environment:
      - POSTGRES_DB=vehicle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '11001:5432'
    volumes:
      - db:/var/lib/postgresql/data
  
  car-service:
    image: fontyssa/car-service
    ports:
      - "11002:80"
    depends_on:
      - db

volumes:
  db:
    driver: local
